/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UyeRouteImport } from './routes/uye'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AnaRouteImport } from './routes/ana'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UyeIndexRouteImport } from './routes/uye/index'
import { Route as OzelProgramIndexRouteImport } from './routes/ozel-program/index'
import { Route as MentorlukIndexRouteImport } from './routes/mentorluk/index'
import { Route as KisiselProgramIndexRouteImport } from './routes/kisisel-program/index'
import { Route as UyeKutuphaneRouteImport } from './routes/uye/kutuphane'
import { Route as UyeGuncellemelerRouteImport } from './routes/uye/guncellemeler'
import { Route as UyeEtkinliklerRouteImport } from './routes/uye/etkinlikler'
import { Route as OzelProgramOdemeRouteImport } from './routes/ozel-program/odeme'
import { Route as MentorlukSatinAlRouteImport } from './routes/mentorluk/satin-al'
import { Route as KisiselProgramOdemeRouteImport } from './routes/kisisel-program/odeme'
import { Route as UyeProfilIndexRouteImport } from './routes/uye/profil/index'
import { Route as UyeDerslerIndexRouteImport } from './routes/uye/dersler/index'
import { Route as UyeProfilVideolarRouteImport } from './routes/uye/profil/videolar'
import { Route as UyeProfilNotlarRouteImport } from './routes/uye/profil/notlar'
import { Route as UyeProfilAyarlarRouteImport } from './routes/uye/profil/ayarlar'
import { Route as UyeDerslerCourseIdRouteImport } from './routes/uye/dersler/$courseId'

const UyeRoute = UyeRouteImport.update({
  id: '/uye',
  path: '/uye',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaRoute = AnaRouteImport.update({
  id: '/ana',
  path: '/ana',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UyeIndexRoute = UyeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UyeRoute,
} as any)
const OzelProgramIndexRoute = OzelProgramIndexRouteImport.update({
  id: '/ozel-program/',
  path: '/ozel-program/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorlukIndexRoute = MentorlukIndexRouteImport.update({
  id: '/mentorluk/',
  path: '/mentorluk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiselProgramIndexRoute = KisiselProgramIndexRouteImport.update({
  id: '/kisisel-program/',
  path: '/kisisel-program/',
  getParentRoute: () => rootRouteImport,
} as any)
const UyeKutuphaneRoute = UyeKutuphaneRouteImport.update({
  id: '/kutuphane',
  path: '/kutuphane',
  getParentRoute: () => UyeRoute,
} as any)
const UyeGuncellemelerRoute = UyeGuncellemelerRouteImport.update({
  id: '/guncellemeler',
  path: '/guncellemeler',
  getParentRoute: () => UyeRoute,
} as any)
const UyeEtkinliklerRoute = UyeEtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => UyeRoute,
} as any)
const OzelProgramOdemeRoute = OzelProgramOdemeRouteImport.update({
  id: '/ozel-program/odeme',
  path: '/ozel-program/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorlukSatinAlRoute = MentorlukSatinAlRouteImport.update({
  id: '/mentorluk/satin-al',
  path: '/mentorluk/satin-al',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiselProgramOdemeRoute = KisiselProgramOdemeRouteImport.update({
  id: '/kisisel-program/odeme',
  path: '/kisisel-program/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const UyeProfilIndexRoute = UyeProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => UyeRoute,
} as any)
const UyeDerslerIndexRoute = UyeDerslerIndexRouteImport.update({
  id: '/dersler/',
  path: '/dersler/',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilVideolarRoute = UyeProfilVideolarRouteImport.update({
  id: '/profil/videolar',
  path: '/profil/videolar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilNotlarRoute = UyeProfilNotlarRouteImport.update({
  id: '/profil/notlar',
  path: '/profil/notlar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilAyarlarRoute = UyeProfilAyarlarRouteImport.update({
  id: '/profil/ayarlar',
  path: '/profil/ayarlar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeDerslerCourseIdRoute = UyeDerslerCourseIdRouteImport.update({
  id: '/dersler/$courseId',
  path: '/dersler/$courseId',
  getParentRoute: () => UyeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/uye': typeof UyeRouteWithChildren
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/kisisel-program/': typeof KisiselProgramIndexRoute
  '/mentorluk/': typeof MentorlukIndexRoute
  '/ozel-program/': typeof OzelProgramIndexRoute
  '/uye/': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler/': typeof UyeDerslerIndexRoute
  '/uye/profil/': typeof UyeProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/kisisel-program': typeof KisiselProgramIndexRoute
  '/mentorluk': typeof MentorlukIndexRoute
  '/ozel-program': typeof OzelProgramIndexRoute
  '/uye': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler': typeof UyeDerslerIndexRoute
  '/uye/profil': typeof UyeProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/uye': typeof UyeRouteWithChildren
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/kisisel-program/': typeof KisiselProgramIndexRoute
  '/mentorluk/': typeof MentorlukIndexRoute
  '/ozel-program/': typeof OzelProgramIndexRoute
  '/uye/': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler/': typeof UyeDerslerIndexRoute
  '/uye/profil/': typeof UyeProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ana'
    | '/forgot-password'
    | '/login'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/uye'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/kisisel-program/'
    | '/mentorluk/'
    | '/ozel-program/'
    | '/uye/'
    | '/uye/dersler/$courseId'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler/'
    | '/uye/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ana'
    | '/forgot-password'
    | '/login'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/kisisel-program'
    | '/mentorluk'
    | '/ozel-program'
    | '/uye'
    | '/uye/dersler/$courseId'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler'
    | '/uye/profil'
  id:
    | '__root__'
    | '/'
    | '/ana'
    | '/forgot-password'
    | '/login'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/uye'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/kisisel-program/'
    | '/mentorluk/'
    | '/ozel-program/'
    | '/uye/'
    | '/uye/dersler/$courseId'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler/'
    | '/uye/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaRoute: typeof AnaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UyeRoute: typeof UyeRouteWithChildren
  KisiselProgramOdemeRoute: typeof KisiselProgramOdemeRoute
  MentorlukSatinAlRoute: typeof MentorlukSatinAlRoute
  OzelProgramOdemeRoute: typeof OzelProgramOdemeRoute
  KisiselProgramIndexRoute: typeof KisiselProgramIndexRoute
  MentorlukIndexRoute: typeof MentorlukIndexRoute
  OzelProgramIndexRoute: typeof OzelProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uye': {
      id: '/uye'
      path: '/uye'
      fullPath: '/uye'
      preLoaderRoute: typeof UyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ana': {
      id: '/ana'
      path: '/ana'
      fullPath: '/ana'
      preLoaderRoute: typeof AnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uye/': {
      id: '/uye/'
      path: '/'
      fullPath: '/uye/'
      preLoaderRoute: typeof UyeIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/ozel-program/': {
      id: '/ozel-program/'
      path: '/ozel-program'
      fullPath: '/ozel-program/'
      preLoaderRoute: typeof OzelProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorluk/': {
      id: '/mentorluk/'
      path: '/mentorluk'
      fullPath: '/mentorluk/'
      preLoaderRoute: typeof MentorlukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisisel-program/': {
      id: '/kisisel-program/'
      path: '/kisisel-program'
      fullPath: '/kisisel-program/'
      preLoaderRoute: typeof KisiselProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uye/kutuphane': {
      id: '/uye/kutuphane'
      path: '/kutuphane'
      fullPath: '/uye/kutuphane'
      preLoaderRoute: typeof UyeKutuphaneRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/guncellemeler': {
      id: '/uye/guncellemeler'
      path: '/guncellemeler'
      fullPath: '/uye/guncellemeler'
      preLoaderRoute: typeof UyeGuncellemelerRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/etkinlikler': {
      id: '/uye/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/uye/etkinlikler'
      preLoaderRoute: typeof UyeEtkinliklerRouteImport
      parentRoute: typeof UyeRoute
    }
    '/ozel-program/odeme': {
      id: '/ozel-program/odeme'
      path: '/ozel-program/odeme'
      fullPath: '/ozel-program/odeme'
      preLoaderRoute: typeof OzelProgramOdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorluk/satin-al': {
      id: '/mentorluk/satin-al'
      path: '/mentorluk/satin-al'
      fullPath: '/mentorluk/satin-al'
      preLoaderRoute: typeof MentorlukSatinAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisisel-program/odeme': {
      id: '/kisisel-program/odeme'
      path: '/kisisel-program/odeme'
      fullPath: '/kisisel-program/odeme'
      preLoaderRoute: typeof KisiselProgramOdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uye/profil/': {
      id: '/uye/profil/'
      path: '/profil'
      fullPath: '/uye/profil/'
      preLoaderRoute: typeof UyeProfilIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/dersler/': {
      id: '/uye/dersler/'
      path: '/dersler'
      fullPath: '/uye/dersler/'
      preLoaderRoute: typeof UyeDerslerIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/videolar': {
      id: '/uye/profil/videolar'
      path: '/profil/videolar'
      fullPath: '/uye/profil/videolar'
      preLoaderRoute: typeof UyeProfilVideolarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/notlar': {
      id: '/uye/profil/notlar'
      path: '/profil/notlar'
      fullPath: '/uye/profil/notlar'
      preLoaderRoute: typeof UyeProfilNotlarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/ayarlar': {
      id: '/uye/profil/ayarlar'
      path: '/profil/ayarlar'
      fullPath: '/uye/profil/ayarlar'
      preLoaderRoute: typeof UyeProfilAyarlarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/dersler/$courseId': {
      id: '/uye/dersler/$courseId'
      path: '/dersler/$courseId'
      fullPath: '/uye/dersler/$courseId'
      preLoaderRoute: typeof UyeDerslerCourseIdRouteImport
      parentRoute: typeof UyeRoute
    }
  }
}

interface UyeRouteChildren {
  UyeEtkinliklerRoute: typeof UyeEtkinliklerRoute
  UyeGuncellemelerRoute: typeof UyeGuncellemelerRoute
  UyeKutuphaneRoute: typeof UyeKutuphaneRoute
  UyeIndexRoute: typeof UyeIndexRoute
  UyeDerslerCourseIdRoute: typeof UyeDerslerCourseIdRoute
  UyeProfilAyarlarRoute: typeof UyeProfilAyarlarRoute
  UyeProfilNotlarRoute: typeof UyeProfilNotlarRoute
  UyeProfilVideolarRoute: typeof UyeProfilVideolarRoute
  UyeDerslerIndexRoute: typeof UyeDerslerIndexRoute
  UyeProfilIndexRoute: typeof UyeProfilIndexRoute
}

const UyeRouteChildren: UyeRouteChildren = {
  UyeEtkinliklerRoute: UyeEtkinliklerRoute,
  UyeGuncellemelerRoute: UyeGuncellemelerRoute,
  UyeKutuphaneRoute: UyeKutuphaneRoute,
  UyeIndexRoute: UyeIndexRoute,
  UyeDerslerCourseIdRoute: UyeDerslerCourseIdRoute,
  UyeProfilAyarlarRoute: UyeProfilAyarlarRoute,
  UyeProfilNotlarRoute: UyeProfilNotlarRoute,
  UyeProfilVideolarRoute: UyeProfilVideolarRoute,
  UyeDerslerIndexRoute: UyeDerslerIndexRoute,
  UyeProfilIndexRoute: UyeProfilIndexRoute,
}

const UyeRouteWithChildren = UyeRoute._addFileChildren(UyeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaRoute: AnaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UyeRoute: UyeRouteWithChildren,
  KisiselProgramOdemeRoute: KisiselProgramOdemeRoute,
  MentorlukSatinAlRoute: MentorlukSatinAlRoute,
  OzelProgramOdemeRoute: OzelProgramOdemeRoute,
  KisiselProgramIndexRoute: KisiselProgramIndexRoute,
  MentorlukIndexRoute: MentorlukIndexRoute,
  OzelProgramIndexRoute: OzelProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
