/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UyeRouteImport } from './routes/uye'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PatikaDemoRouteImport } from './routes/patika-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GecicihubRouteImport } from './routes/gecicihub'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AnaRouteImport } from './routes/ana'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UyeIndexRouteImport } from './routes/uye/index'
import { Route as OzelProgramIndexRouteImport } from './routes/ozel-program/index'
import { Route as MentorlukIndexRouteImport } from './routes/mentorluk/index'
import { Route as KisiselProgramIndexRouteImport } from './routes/kisisel-program/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UyeToplulukRouteImport } from './routes/uye/topluluk'
import { Route as UyeKutuphaneRouteImport } from './routes/uye/kutuphane'
import { Route as UyeGuncellemelerRouteImport } from './routes/uye/guncellemeler'
import { Route as UyeEtkinliklerRouteImport } from './routes/uye/etkinlikler'
import { Route as OzelProgramOdemeRouteImport } from './routes/ozel-program/odeme'
import { Route as MentorlukTesekkurlerRouteImport } from './routes/mentorluk/tesekkurler'
import { Route as MentorlukSatinAlRouteImport } from './routes/mentorluk/satin-al'
import { Route as KisiselProgramOdemeRouteImport } from './routes/kisisel-program/odeme'
import { Route as AdminKurslarRouteImport } from './routes/admin/kurslar'
import { Route as AdminGuncellemelerRouteImport } from './routes/admin/guncellemeler'
import { Route as AdminFiyatKontrolRouteImport } from './routes/admin/fiyat-kontrol'
import { Route as AdminEtkinliklerRouteImport } from './routes/admin/etkinlikler'
import { Route as AdminBeklemeListesiRouteImport } from './routes/admin/bekleme-listesi'
import { Route as UyeProfilIndexRouteImport } from './routes/uye/profil/index'
import { Route as UyeDerslerIndexRouteImport } from './routes/uye/dersler/index'
import { Route as UyeProfilVideolarRouteImport } from './routes/uye/profil/videolar'
import { Route as UyeProfilNotlarRouteImport } from './routes/uye/profil/notlar'
import { Route as UyeProfilAyarlarRouteImport } from './routes/uye/profil/ayarlar'
import { Route as UyeProfilAbonelikRouteImport } from './routes/uye/profil/abonelik'
import { Route as UyeDerslerCourseIdRouteImport } from './routes/uye/dersler/$courseId'

const UyeRoute = UyeRouteImport.update({
  id: '/uye',
  path: '/uye',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PatikaDemoRoute = PatikaDemoRouteImport.update({
  id: '/patika-demo',
  path: '/patika-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GecicihubRoute = GecicihubRouteImport.update({
  id: '/gecicihub',
  path: '/gecicihub',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaRoute = AnaRouteImport.update({
  id: '/ana',
  path: '/ana',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UyeIndexRoute = UyeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UyeRoute,
} as any)
const OzelProgramIndexRoute = OzelProgramIndexRouteImport.update({
  id: '/ozel-program/',
  path: '/ozel-program/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorlukIndexRoute = MentorlukIndexRouteImport.update({
  id: '/mentorluk/',
  path: '/mentorluk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiselProgramIndexRoute = KisiselProgramIndexRouteImport.update({
  id: '/kisisel-program/',
  path: '/kisisel-program/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UyeToplulukRoute = UyeToplulukRouteImport.update({
  id: '/topluluk',
  path: '/topluluk',
  getParentRoute: () => UyeRoute,
} as any)
const UyeKutuphaneRoute = UyeKutuphaneRouteImport.update({
  id: '/kutuphane',
  path: '/kutuphane',
  getParentRoute: () => UyeRoute,
} as any)
const UyeGuncellemelerRoute = UyeGuncellemelerRouteImport.update({
  id: '/guncellemeler',
  path: '/guncellemeler',
  getParentRoute: () => UyeRoute,
} as any)
const UyeEtkinliklerRoute = UyeEtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => UyeRoute,
} as any)
const OzelProgramOdemeRoute = OzelProgramOdemeRouteImport.update({
  id: '/ozel-program/odeme',
  path: '/ozel-program/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorlukTesekkurlerRoute = MentorlukTesekkurlerRouteImport.update({
  id: '/mentorluk/tesekkurler',
  path: '/mentorluk/tesekkurler',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorlukSatinAlRoute = MentorlukSatinAlRouteImport.update({
  id: '/mentorluk/satin-al',
  path: '/mentorluk/satin-al',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiselProgramOdemeRoute = KisiselProgramOdemeRouteImport.update({
  id: '/kisisel-program/odeme',
  path: '/kisisel-program/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKurslarRoute = AdminKurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuncellemelerRoute = AdminGuncellemelerRouteImport.update({
  id: '/guncellemeler',
  path: '/guncellemeler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiyatKontrolRoute = AdminFiyatKontrolRouteImport.update({
  id: '/fiyat-kontrol',
  path: '/fiyat-kontrol',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtkinliklerRoute = AdminEtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeklemeListesiRoute = AdminBeklemeListesiRouteImport.update({
  id: '/bekleme-listesi',
  path: '/bekleme-listesi',
  getParentRoute: () => AdminRoute,
} as any)
const UyeProfilIndexRoute = UyeProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => UyeRoute,
} as any)
const UyeDerslerIndexRoute = UyeDerslerIndexRouteImport.update({
  id: '/dersler/',
  path: '/dersler/',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilVideolarRoute = UyeProfilVideolarRouteImport.update({
  id: '/profil/videolar',
  path: '/profil/videolar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilNotlarRoute = UyeProfilNotlarRouteImport.update({
  id: '/profil/notlar',
  path: '/profil/notlar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilAyarlarRoute = UyeProfilAyarlarRouteImport.update({
  id: '/profil/ayarlar',
  path: '/profil/ayarlar',
  getParentRoute: () => UyeRoute,
} as any)
const UyeProfilAbonelikRoute = UyeProfilAbonelikRouteImport.update({
  id: '/profil/abonelik',
  path: '/profil/abonelik',
  getParentRoute: () => UyeRoute,
} as any)
const UyeDerslerCourseIdRoute = UyeDerslerCourseIdRouteImport.update({
  id: '/dersler/$courseId',
  path: '/dersler/$courseId',
  getParentRoute: () => UyeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gecicihub': typeof GecicihubRoute
  '/login': typeof LoginRoute
  '/patika-demo': typeof PatikaDemoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/uye': typeof UyeRouteWithChildren
  '/admin/bekleme-listesi': typeof AdminBeklemeListesiRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/fiyat-kontrol': typeof AdminFiyatKontrolRoute
  '/admin/guncellemeler': typeof AdminGuncellemelerRoute
  '/admin/kurslar': typeof AdminKurslarRoute
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/mentorluk/tesekkurler': typeof MentorlukTesekkurlerRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/uye/topluluk': typeof UyeToplulukRoute
  '/admin/': typeof AdminIndexRoute
  '/kisisel-program/': typeof KisiselProgramIndexRoute
  '/mentorluk/': typeof MentorlukIndexRoute
  '/ozel-program/': typeof OzelProgramIndexRoute
  '/uye/': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/abonelik': typeof UyeProfilAbonelikRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler/': typeof UyeDerslerIndexRoute
  '/uye/profil/': typeof UyeProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gecicihub': typeof GecicihubRoute
  '/login': typeof LoginRoute
  '/patika-demo': typeof PatikaDemoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/bekleme-listesi': typeof AdminBeklemeListesiRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/fiyat-kontrol': typeof AdminFiyatKontrolRoute
  '/admin/guncellemeler': typeof AdminGuncellemelerRoute
  '/admin/kurslar': typeof AdminKurslarRoute
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/mentorluk/tesekkurler': typeof MentorlukTesekkurlerRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/uye/topluluk': typeof UyeToplulukRoute
  '/admin': typeof AdminIndexRoute
  '/kisisel-program': typeof KisiselProgramIndexRoute
  '/mentorluk': typeof MentorlukIndexRoute
  '/ozel-program': typeof OzelProgramIndexRoute
  '/uye': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/abonelik': typeof UyeProfilAbonelikRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler': typeof UyeDerslerIndexRoute
  '/uye/profil': typeof UyeProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ana': typeof AnaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gecicihub': typeof GecicihubRoute
  '/login': typeof LoginRoute
  '/patika-demo': typeof PatikaDemoRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/playground': typeof PlaygroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/uye': typeof UyeRouteWithChildren
  '/admin/bekleme-listesi': typeof AdminBeklemeListesiRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/fiyat-kontrol': typeof AdminFiyatKontrolRoute
  '/admin/guncellemeler': typeof AdminGuncellemelerRoute
  '/admin/kurslar': typeof AdminKurslarRoute
  '/kisisel-program/odeme': typeof KisiselProgramOdemeRoute
  '/mentorluk/satin-al': typeof MentorlukSatinAlRoute
  '/mentorluk/tesekkurler': typeof MentorlukTesekkurlerRoute
  '/ozel-program/odeme': typeof OzelProgramOdemeRoute
  '/uye/etkinlikler': typeof UyeEtkinliklerRoute
  '/uye/guncellemeler': typeof UyeGuncellemelerRoute
  '/uye/kutuphane': typeof UyeKutuphaneRoute
  '/uye/topluluk': typeof UyeToplulukRoute
  '/admin/': typeof AdminIndexRoute
  '/kisisel-program/': typeof KisiselProgramIndexRoute
  '/mentorluk/': typeof MentorlukIndexRoute
  '/ozel-program/': typeof OzelProgramIndexRoute
  '/uye/': typeof UyeIndexRoute
  '/uye/dersler/$courseId': typeof UyeDerslerCourseIdRoute
  '/uye/profil/abonelik': typeof UyeProfilAbonelikRoute
  '/uye/profil/ayarlar': typeof UyeProfilAyarlarRoute
  '/uye/profil/notlar': typeof UyeProfilNotlarRoute
  '/uye/profil/videolar': typeof UyeProfilVideolarRoute
  '/uye/dersler/': typeof UyeDerslerIndexRoute
  '/uye/profil/': typeof UyeProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ana'
    | '/forgot-password'
    | '/gecicihub'
    | '/login'
    | '/patika-demo'
    | '/payment-success'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/uye'
    | '/admin/bekleme-listesi'
    | '/admin/etkinlikler'
    | '/admin/fiyat-kontrol'
    | '/admin/guncellemeler'
    | '/admin/kurslar'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/mentorluk/tesekkurler'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/uye/topluluk'
    | '/admin/'
    | '/kisisel-program/'
    | '/mentorluk/'
    | '/ozel-program/'
    | '/uye/'
    | '/uye/dersler/$courseId'
    | '/uye/profil/abonelik'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler/'
    | '/uye/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ana'
    | '/forgot-password'
    | '/gecicihub'
    | '/login'
    | '/patika-demo'
    | '/payment-success'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/admin/bekleme-listesi'
    | '/admin/etkinlikler'
    | '/admin/fiyat-kontrol'
    | '/admin/guncellemeler'
    | '/admin/kurslar'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/mentorluk/tesekkurler'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/uye/topluluk'
    | '/admin'
    | '/kisisel-program'
    | '/mentorluk'
    | '/ozel-program'
    | '/uye'
    | '/uye/dersler/$courseId'
    | '/uye/profil/abonelik'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler'
    | '/uye/profil'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ana'
    | '/forgot-password'
    | '/gecicihub'
    | '/login'
    | '/patika-demo'
    | '/payment-success'
    | '/playground'
    | '/reset-password'
    | '/signup'
    | '/uye'
    | '/admin/bekleme-listesi'
    | '/admin/etkinlikler'
    | '/admin/fiyat-kontrol'
    | '/admin/guncellemeler'
    | '/admin/kurslar'
    | '/kisisel-program/odeme'
    | '/mentorluk/satin-al'
    | '/mentorluk/tesekkurler'
    | '/ozel-program/odeme'
    | '/uye/etkinlikler'
    | '/uye/guncellemeler'
    | '/uye/kutuphane'
    | '/uye/topluluk'
    | '/admin/'
    | '/kisisel-program/'
    | '/mentorluk/'
    | '/ozel-program/'
    | '/uye/'
    | '/uye/dersler/$courseId'
    | '/uye/profil/abonelik'
    | '/uye/profil/ayarlar'
    | '/uye/profil/notlar'
    | '/uye/profil/videolar'
    | '/uye/dersler/'
    | '/uye/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnaRoute: typeof AnaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GecicihubRoute: typeof GecicihubRoute
  LoginRoute: typeof LoginRoute
  PatikaDemoRoute: typeof PatikaDemoRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UyeRoute: typeof UyeRouteWithChildren
  KisiselProgramOdemeRoute: typeof KisiselProgramOdemeRoute
  MentorlukSatinAlRoute: typeof MentorlukSatinAlRoute
  MentorlukTesekkurlerRoute: typeof MentorlukTesekkurlerRoute
  OzelProgramOdemeRoute: typeof OzelProgramOdemeRoute
  KisiselProgramIndexRoute: typeof KisiselProgramIndexRoute
  MentorlukIndexRoute: typeof MentorlukIndexRoute
  OzelProgramIndexRoute: typeof OzelProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uye': {
      id: '/uye'
      path: '/uye'
      fullPath: '/uye'
      preLoaderRoute: typeof UyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patika-demo': {
      id: '/patika-demo'
      path: '/patika-demo'
      fullPath: '/patika-demo'
      preLoaderRoute: typeof PatikaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gecicihub': {
      id: '/gecicihub'
      path: '/gecicihub'
      fullPath: '/gecicihub'
      preLoaderRoute: typeof GecicihubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ana': {
      id: '/ana'
      path: '/ana'
      fullPath: '/ana'
      preLoaderRoute: typeof AnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uye/': {
      id: '/uye/'
      path: '/'
      fullPath: '/uye/'
      preLoaderRoute: typeof UyeIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/ozel-program/': {
      id: '/ozel-program/'
      path: '/ozel-program'
      fullPath: '/ozel-program/'
      preLoaderRoute: typeof OzelProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorluk/': {
      id: '/mentorluk/'
      path: '/mentorluk'
      fullPath: '/mentorluk/'
      preLoaderRoute: typeof MentorlukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisisel-program/': {
      id: '/kisisel-program/'
      path: '/kisisel-program'
      fullPath: '/kisisel-program/'
      preLoaderRoute: typeof KisiselProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/uye/topluluk': {
      id: '/uye/topluluk'
      path: '/topluluk'
      fullPath: '/uye/topluluk'
      preLoaderRoute: typeof UyeToplulukRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/kutuphane': {
      id: '/uye/kutuphane'
      path: '/kutuphane'
      fullPath: '/uye/kutuphane'
      preLoaderRoute: typeof UyeKutuphaneRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/guncellemeler': {
      id: '/uye/guncellemeler'
      path: '/guncellemeler'
      fullPath: '/uye/guncellemeler'
      preLoaderRoute: typeof UyeGuncellemelerRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/etkinlikler': {
      id: '/uye/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/uye/etkinlikler'
      preLoaderRoute: typeof UyeEtkinliklerRouteImport
      parentRoute: typeof UyeRoute
    }
    '/ozel-program/odeme': {
      id: '/ozel-program/odeme'
      path: '/ozel-program/odeme'
      fullPath: '/ozel-program/odeme'
      preLoaderRoute: typeof OzelProgramOdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorluk/tesekkurler': {
      id: '/mentorluk/tesekkurler'
      path: '/mentorluk/tesekkurler'
      fullPath: '/mentorluk/tesekkurler'
      preLoaderRoute: typeof MentorlukTesekkurlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorluk/satin-al': {
      id: '/mentorluk/satin-al'
      path: '/mentorluk/satin-al'
      fullPath: '/mentorluk/satin-al'
      preLoaderRoute: typeof MentorlukSatinAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisisel-program/odeme': {
      id: '/kisisel-program/odeme'
      path: '/kisisel-program/odeme'
      fullPath: '/kisisel-program/odeme'
      preLoaderRoute: typeof KisiselProgramOdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kurslar': {
      id: '/admin/kurslar'
      path: '/kurslar'
      fullPath: '/admin/kurslar'
      preLoaderRoute: typeof AdminKurslarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guncellemeler': {
      id: '/admin/guncellemeler'
      path: '/guncellemeler'
      fullPath: '/admin/guncellemeler'
      preLoaderRoute: typeof AdminGuncellemelerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fiyat-kontrol': {
      id: '/admin/fiyat-kontrol'
      path: '/fiyat-kontrol'
      fullPath: '/admin/fiyat-kontrol'
      preLoaderRoute: typeof AdminFiyatKontrolRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etkinlikler': {
      id: '/admin/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/admin/etkinlikler'
      preLoaderRoute: typeof AdminEtkinliklerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bekleme-listesi': {
      id: '/admin/bekleme-listesi'
      path: '/bekleme-listesi'
      fullPath: '/admin/bekleme-listesi'
      preLoaderRoute: typeof AdminBeklemeListesiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/uye/profil/': {
      id: '/uye/profil/'
      path: '/profil'
      fullPath: '/uye/profil/'
      preLoaderRoute: typeof UyeProfilIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/dersler/': {
      id: '/uye/dersler/'
      path: '/dersler'
      fullPath: '/uye/dersler/'
      preLoaderRoute: typeof UyeDerslerIndexRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/videolar': {
      id: '/uye/profil/videolar'
      path: '/profil/videolar'
      fullPath: '/uye/profil/videolar'
      preLoaderRoute: typeof UyeProfilVideolarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/notlar': {
      id: '/uye/profil/notlar'
      path: '/profil/notlar'
      fullPath: '/uye/profil/notlar'
      preLoaderRoute: typeof UyeProfilNotlarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/ayarlar': {
      id: '/uye/profil/ayarlar'
      path: '/profil/ayarlar'
      fullPath: '/uye/profil/ayarlar'
      preLoaderRoute: typeof UyeProfilAyarlarRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/profil/abonelik': {
      id: '/uye/profil/abonelik'
      path: '/profil/abonelik'
      fullPath: '/uye/profil/abonelik'
      preLoaderRoute: typeof UyeProfilAbonelikRouteImport
      parentRoute: typeof UyeRoute
    }
    '/uye/dersler/$courseId': {
      id: '/uye/dersler/$courseId'
      path: '/dersler/$courseId'
      fullPath: '/uye/dersler/$courseId'
      preLoaderRoute: typeof UyeDerslerCourseIdRouteImport
      parentRoute: typeof UyeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBeklemeListesiRoute: typeof AdminBeklemeListesiRoute
  AdminEtkinliklerRoute: typeof AdminEtkinliklerRoute
  AdminFiyatKontrolRoute: typeof AdminFiyatKontrolRoute
  AdminGuncellemelerRoute: typeof AdminGuncellemelerRoute
  AdminKurslarRoute: typeof AdminKurslarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBeklemeListesiRoute: AdminBeklemeListesiRoute,
  AdminEtkinliklerRoute: AdminEtkinliklerRoute,
  AdminFiyatKontrolRoute: AdminFiyatKontrolRoute,
  AdminGuncellemelerRoute: AdminGuncellemelerRoute,
  AdminKurslarRoute: AdminKurslarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UyeRouteChildren {
  UyeEtkinliklerRoute: typeof UyeEtkinliklerRoute
  UyeGuncellemelerRoute: typeof UyeGuncellemelerRoute
  UyeKutuphaneRoute: typeof UyeKutuphaneRoute
  UyeToplulukRoute: typeof UyeToplulukRoute
  UyeIndexRoute: typeof UyeIndexRoute
  UyeDerslerCourseIdRoute: typeof UyeDerslerCourseIdRoute
  UyeProfilAbonelikRoute: typeof UyeProfilAbonelikRoute
  UyeProfilAyarlarRoute: typeof UyeProfilAyarlarRoute
  UyeProfilNotlarRoute: typeof UyeProfilNotlarRoute
  UyeProfilVideolarRoute: typeof UyeProfilVideolarRoute
  UyeDerslerIndexRoute: typeof UyeDerslerIndexRoute
  UyeProfilIndexRoute: typeof UyeProfilIndexRoute
}

const UyeRouteChildren: UyeRouteChildren = {
  UyeEtkinliklerRoute: UyeEtkinliklerRoute,
  UyeGuncellemelerRoute: UyeGuncellemelerRoute,
  UyeKutuphaneRoute: UyeKutuphaneRoute,
  UyeToplulukRoute: UyeToplulukRoute,
  UyeIndexRoute: UyeIndexRoute,
  UyeDerslerCourseIdRoute: UyeDerslerCourseIdRoute,
  UyeProfilAbonelikRoute: UyeProfilAbonelikRoute,
  UyeProfilAyarlarRoute: UyeProfilAyarlarRoute,
  UyeProfilNotlarRoute: UyeProfilNotlarRoute,
  UyeProfilVideolarRoute: UyeProfilVideolarRoute,
  UyeDerslerIndexRoute: UyeDerslerIndexRoute,
  UyeProfilIndexRoute: UyeProfilIndexRoute,
}

const UyeRouteWithChildren = UyeRoute._addFileChildren(UyeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnaRoute: AnaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GecicihubRoute: GecicihubRoute,
  LoginRoute: LoginRoute,
  PatikaDemoRoute: PatikaDemoRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UyeRoute: UyeRouteWithChildren,
  KisiselProgramOdemeRoute: KisiselProgramOdemeRoute,
  MentorlukSatinAlRoute: MentorlukSatinAlRoute,
  MentorlukTesekkurlerRoute: MentorlukTesekkurlerRoute,
  OzelProgramOdemeRoute: OzelProgramOdemeRoute,
  KisiselProgramIndexRoute: KisiselProgramIndexRoute,
  MentorlukIndexRoute: MentorlukIndexRoute,
  OzelProgramIndexRoute: OzelProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
